# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('releaseDate', models.DateTimeField()),
                ('numSongs', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('avgRating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('isActive', models.BooleanField()),
                ('numAlbums', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('releaseDate', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('avgRating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musik.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musik.Artist'),
        ),
    ]
